### PR TITLE
Finalize Story Building flows

### PR DESCRIPTION
**Pull request by Moiz1524**

### CODE REVIEW

**Comment by sdnorm** [comment]
Prompts aren't deleting


https://github.com/SuperDupr/builder/assets/4260841/852bfe94-4b6f-4bcb-a2f0-acf26677b0f1

**Comment by sdnorm** [comment]
Can we move the `Save as Draft` button over above the `Next Question` button? Make it where the `Private` toggle is right next to it. And move the `My  Stories` section up. 

image

**Comment by Moiz1524** [comment]
> Prompts aren't deleting
> 
>  Screen.Recording.2023-09-06.at.10.29.46.AM.mov

Follow-up the slack comment:

https://splglobal.slack.com/archives/C05D85PJ1EW/p1694073179209889?thread_ts=1693930818.179449&cid=C05D85PJ1EW

**Comment by imranhayat** [comment]
> Can we move the `Save as Draft` button over above the `Next Question` button? Make it where the `Private` toggle is right next to it, but still to the left of the button. And move the `My Stories` section up.


@sdnorm I have changed place of `Save as Draft` button. Let me know if this you wanted.
image

**Comment by sdnorm** [comment]
> > Can we move the `Save as Draft` button over above the `Next Question` button? Make it where the `Private` toggle is right next to it, but still to the left of the button. And move the `My Stories` section up.
> 
> @sdnorm I have changed place of `Save as Draft` button. Let me know if this you wanted. image

That is what I was looking for. Thanks! Can you add a little padding to between the word `Public` and the `Save as Draft` button?

**Comment by imranhayat** [comment]
> @imranhayat That is what I was looking for. Thanks! Can you add a little padding to between the word `Public` and the `Save as Draft` button?

@sdnorm Done.
image

**Review by sdnorm — APPROVED** [review]
Looking good! Will have more feedback but I'll save that for a backlog. 

🚀

**Pull request merged**
