### PR TITLE
AI Powered Builders

### PR DESCRIPTION
**Pull request by Moiz1524**

### CODE REVIEW

**Comment by Moiz1524** [comment]
> @Moiz1524 Can you fix the two conflicts? For the `development.yml.enc` we should keep the main branch. Not sure on the other conflict.

Yes I'm doing that

**Comment by sdnorm** [comment]
@imranhayat Some spacing issues. 

image

**Comment by sdnorm** [comment]
@Moiz1524 When getting a "metaphor" I keep getting this response ...

```I work in the technology industry. My role is in the sales department. The focus of my communication is providing briefs and instructions to external agencies for advertising and creative campaigns. My job title is a producer.```

Is this the expected behavior?

**Comment by sdnorm** [comment]
Show pages of a builder is giving this error. `http://localhost:3000/admin/story_builders/2`

image

**Comment by sdnorm** [comment]
> @Moiz1524 When getting a "metaphor" I keep getting this response ...
> 
> `I work in the technology industry. My role is in the sales department. The focus of my communication is providing briefs and instructions to external agencies for advertising and creative campaigns. My job title is a producer.`
> 
> Is this the expected behavior?
> 
> image

I realized that this is not the case when an Admin AI prompt is used.

**Comment by Moiz1524** [comment]
> > @Moiz1524 When getting a "metaphor" I keep getting this response ...
> > `I work in the technology industry. My role is in the sales department. The focus of my communication is providing briefs and instructions to external agencies for advertising and creative campaigns. My job title is a producer.`
> > Is this the expected behavior?
> > image
> 
> I realized that this is not the case when an Admin AI prompt is used.

Yes Spencer. Now we have to check and improvise over Admin AI prompt. I've removed the System AI prompt from system

**Comment by imranhayat** [comment]
> @imranhayat Some spacing issues.
> 
> image

@sdnorm Can you please share your full screen and the select dropdown options, because this design is fine on my end.

**Comment by sdnorm** [comment]
The styling of the drop down inputs is great. One missing piece is the styling of the actual drop downs. Can we get those styled instead of browser default? @imranhayat 

image

**Comment by imranhayat** [comment]
> > > @imranhayat Some spacing issues.
> > > image
> > 
> > 
> > @sdnorm Can you please share your full screen and the select dropdown options, because this design is fine on my end.
> 
> I understand that some of the options are longer in characters. Can we add some view logic to reduce the font size inside of that container? I think a slight, general reduction in font size inside the container would help too.

@sdnorm I have done this but I have got few edge cases in the logic of the select. I will discuss this tomorrow with Moiz and will update you. About the design you can review this [PR](https://github.com/SuperDupr/builder/pull/135)

**Comment by imranhayat** [comment]
> The styling of the drop down inputs is great. One missing piece is the styling of the actual drop downs. Can we get those styled instead of browser default? @imranhayat
> 
> image

@sdnorm No we can't style select option according to figma. we can change background of wole select option but can't change the background of selected option.

**Review by sdnorm — APPROVED** [review]

**Pull request merged**
