### PR TITLE
Enable Teams management for Organization Admin

### PR DESCRIPTION
**Pull request by Moiz1524**
## Description
Teams Management (CRUD operations) for Organization Admin

### CODE REVIEW

**Comment by sdnorm** [comment]
@Moiz1524 Is this ready for me to review?

**Comment by Moiz1524** [comment]
> @Moiz1524 Is this ready for me to review?

Yes it's ready for review

**Comment by sdnorm** [comment]
When I am logged in as a `super admin` I see the ability to manage `teams`. However, when I am logged in as an `org admin` I do not see the ability to manage `teams` on the `org`.

**Comment by Moiz1524** [comment]
> When I am logged in as a `super admin` I see the ability to manage `teams`. However, when I am logged in as an `org admin` I do not see the ability to manage `teams` on the `org`.

We have catered this inside #42

**Review by sdnorm — APPROVED** [review]

**Pull request merged**
